/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/types.json
export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  event?: EventReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: "seminar" | "competition";
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  date?: string;
  startDate?: string;
  finishDate?: string;
  fullDay?: boolean;
  location?: {
    geo?: Geopoint;
    placeName?: string;
    address?: string;
  };
  description?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  date?: string;
  description?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type GeopointRadius = {
  _type: "geopointRadius";
  lat?: number;
  lng?: number;
  alt?: number;
  radius?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | EventReference
  | SanityImageAssetReference
  | Certificate
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | Geopoint
  | Slug
  | Article
  | GeopointRadius
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: src/sanity/queries/article.ts
// Variable: ArticleQuery
// Query: *[_type == "article" && defined(slug.current)][0]{  _id,  title,  slug,  date,  image}
export type ArticleQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries/article.ts
// Variable: ArticleQueryFull
// Query: *[_type == "article" && defined(slug.current)][0]{  _id,  title,  slug,  date,  image,  content}
export type ArticleQueryFullResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/queries/certificate.ts
// Variable: CertificateQuery
// Query: *[_type == "certificate" && event._ref == $eventId][0]{event->{_id, title, startDate, finishDate, fullDay}, image}
export type CertificateQueryResult = {
  event: {
    _id: string;
    title: string | null;
    startDate: string | null;
    finishDate: string | null;
    fullDay: boolean | null;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries/event.ts
// Variable: EventsQuery
// Query: *[  _type == "event"  && defined(slug.current)  && (!defined($type) || type == $type)]|order(date desc)[$start...$end]{  _id,  type,  title,  slug,  date,  startDate,  finishDate,  fullDay,  location,  image}
export type EventsQueryResult = Array<{
  _id: string;
  type: "competition" | "seminar" | null;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  startDate: string | null;
  finishDate: string | null;
  fullDay: boolean | null;
  location: {
    geo?: Geopoint;
    placeName?: string;
    address?: string;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries/event.ts
// Variable: EventQuery
// Query: *[_type == "event" && slug.current == $slug][0]{  _id,  type,  title,  slug,  date,  startDate,  finishDate,  fullDay,  location,  image}
export type EventQueryResult = {
  _id: string;
  type: "competition" | "seminar" | null;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  startDate: string | null;
  finishDate: string | null;
  fullDay: boolean | null;
  location: {
    geo?: Geopoint;
    placeName?: string;
    address?: string;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries/event.ts
// Variable: EventQueryFull
// Query: *[_type == "event" && slug.current == $slug][0]{  _id,  type,  title,  slug,  date,  startDate,  finishDate,  fullDay,  location,  image,  content,  "hasCertificate": count(*[_type == "certificate" && event._ref == ^._id]) > 0}
export type EventQueryFullResult = {
  _id: string;
  type: "competition" | "seminar" | null;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  startDate: string | null;
  finishDate: string | null;
  fullDay: boolean | null;
  location: {
    geo?: Geopoint;
    placeName?: string;
    address?: string;
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  hasCertificate: boolean;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n*[_type == "article" && defined(slug.current)][0]\n{\n  _id,\n  title,\n  slug,\n  date,\n  image\n}\n': ArticleQueryResult;
    '\n*[_type == "article" && defined(slug.current)][0]\n{\n  _id,\n  title,\n  slug,\n  date,\n  image,\n  content\n}\n': ArticleQueryFullResult;
    '\n*[_type == "certificate" && event._ref == $eventId][0]\n{event->{_id, title, startDate, finishDate, fullDay}, image}\n': CertificateQueryResult;
    '\n*[\n  _type == "event"\n  && defined(slug.current)\n  && (!defined($type) || type == $type)\n]\n|order(date desc)[$start...$end]\n{\n  _id,\n  type,\n  title,\n  slug,\n  date,\n  startDate,\n  finishDate,\n  fullDay,\n  location,\n  image\n}\n': EventsQueryResult;
    '\n*[_type == "event" && slug.current == $slug][0]\n{\n  _id,\n  type,\n  title,\n  slug,\n  date,\n  startDate,\n  finishDate,\n  fullDay,\n  location,\n  image\n}\n': EventQueryResult;
    '\n*[_type == "event" && slug.current == $slug][0]\n{\n  _id,\n  type,\n  title,\n  slug,\n  date,\n  startDate,\n  finishDate,\n  fullDay,\n  location,\n  image,\n  content,\n  "hasCertificate": count(*[_type == "certificate" && event._ref == ^._id]) > 0\n}\n': EventQueryFullResult;
  }
}
