import { ThemeProvider } from "flowbite-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { PropsWithChildren } from "react";
import "./globals.css";
import theme from "./theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PSHT Cabang Salatiga",
  // description: "Generated by create next app",
};

export default function ClientLayout({ children }: PropsWithChildren) {
  return (
    <ThemeProvider theme={theme}>
      <html
        lang="id"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-screen flex flex-col">{children}</body>
      </html>
    </ThemeProvider>
  );
}
