name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DEPLOY_ENV=Production" >> $GITHUB_ENV
            echo "DEPLOY_DOMAIN=pshtcabangsalatiga.vercel.app" >> $GITHUB_ENV
            npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
          else
            echo "DEPLOY_ENV=Preview" >> $GITHUB_ENV
            echo "DEPLOY_DOMAIN=pshtcabangsalatiga.or.id" >> $GITHUB_ENV
            npx vercel --yes --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Send email
        if: success()
        uses: dawidd6/action-send-mail@v17
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          from: "GitHub CI <media.pshtcabangsalatiga@gmail.com>"
          to: fajarnurprasetyo.2@gmail.com, gustianrauf@gmail.com
          subject: "🚀 ${{ env.DEPLOY_ENV }} deployed"
          convert_markdown: true
          html_body: |
            ## Deployment Info
            <table border="1" cellpadding="8" style="border-collapse: collapse;">
              <tr>
                <td><b>Repository</b></td>
                <td>${{ github.repository }}</td>
              </tr>
              <tr>
                <td><b>Branch</b></td>
                <td>${{ github.ref_name }}</td>
              </tr>
              <tr>
                <td><b>Author</b></td>
                <td>${{ github.actor }}</td>
              </tr>
              <tr>
                <td><b>Domain</b></td>
                <td>
                  <a href="${{ env.DEPLOY_DOMAIN }}">
                    ${{ env.DEPLOY_DOMAIN }}
                  </a>
                </td>
              </tr>
            </table>

            ## Commit Message
            ${{ github.event.head_commit.message }}
