name: Send Email on Push

on: push

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v17
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          from: "GitHub CI <media.pshtcabangsalatiga@gmail.com>"
          to: fajarnurprasetyo.2@gmail.com
          subject: "🚀 Push Baru - ${{ github.ref_name }}"
          body: |
            <h2>🚀 Push Baru</h2>
            <p><b>Repo:</b> ${{ github.repository }}</p>
            <p><b>Branch:</b> ${{ github.ref_name }}</p>
            <p><b>Author:</b> ${{ github.actor }}</p>
            <p><b>Message:</b> ${{ github.event.head_commit.message }}</p>
